"""
Model upload to HuggingFace Hub for Akash Unsloth Fine-tune Demo.

Uploads LoRA adapters and optionally merged model to HuggingFace Hub.
Falls back to HTTP serving on port 8080 if upload fails.
"""

import json
import logging
import os
import sys
import time
from pathlib import Path

logger = logging.getLogger("finetune.upload")

# Retry configuration
MAX_RETRIES = 3
RETRY_DELAYS = [5, 15, 45]  # Exponential backoff in seconds


def upload_to_huggingface(
    lora_dir: str,
    merged_dir: str,
    repo_id: str,
    token: str,
    push_adapters: bool = True,
    push_merged: bool = True,
) -> bool:
    """Upload model artifacts to HuggingFace Hub with retry logic."""
    from huggingface_hub import HfApi, create_repo

    api = HfApi(token=token)

    # Ensure repo exists
    try:
        create_repo(repo_id=repo_id, exist_ok=True, token=token)
        logger.info("HuggingFace repo ready: %s", repo_id)
    except Exception as e:
        logger.error("Failed to create/access HF repo '%s': %s", repo_id, e)
        return False

    success = True

    # Upload LoRA adapters
    if push_adapters and os.path.isdir(lora_dir):
        logger.info("Uploading LoRA adapters to %s/lora-adapters", repo_id)
        if not _retry_upload(api, lora_dir, repo_id, path_in_repo="lora-adapters"):
            success = False

    # Upload merged model
    if push_merged and os.path.isdir(merged_dir):
        logger.info("Uploading merged model to %s/merged", repo_id)
        if not _retry_upload(api, merged_dir, repo_id, path_in_repo="merged"):
            success = False

    # Create model card
    if success:
        _create_model_card(api, repo_id, lora_dir)

    return success


def _retry_upload(api, folder_path: str, repo_id: str, path_in_repo: str) -> bool:
    """Upload folder to HF Hub with exponential backoff retry."""
    for attempt in range(MAX_RETRIES):
        try:
            api.upload_folder(
                folder_path=folder_path,
                repo_id=repo_id,
                repo_type="model",
                path_in_repo=path_in_repo,
            )
            logger.info("Upload successful: %s -> %s/%s", folder_path, repo_id, path_in_repo)
            return True
        except Exception as e:
            delay = RETRY_DELAYS[min(attempt, len(RETRY_DELAYS) - 1)]
            logger.warning("Upload attempt %d/%d failed: %s. Retrying in %ds...",
                         attempt + 1, MAX_RETRIES, e, delay)
            if attempt < MAX_RETRIES - 1:
                time.sleep(delay)
            else:
                logger.error("Upload failed after %d attempts: %s", MAX_RETRIES, e)
                return False
    return False


def _create_model_card(api, repo_id: str, lora_dir: str) -> None:
    """Create a model card README on HuggingFace Hub."""
    model_card = f"""# {repo_id}

## Model Description
Fine-tuned using QLoRA with Unsloth on Akash H200 GPU.

## Training Details
- **Base Model:** unsloth/qwen3.5-4b-instruct-bnb-4bit
- **Method:** QLoRA (4-bit quantization + LoRA adapters)
- **Dataset:** OpenBMB/OlympiadBench (~5K samples)
- **Framework:** Unsloth + HuggingFace TRL

## Artifacts
- `lora-adapters/` - LoRA adapter weights
- `merged/` - Merged model (16-bit)

## Usage
```python
from unsloth import FastLanguageModel

# Load adapters
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="{repo_id}/lora-adapters",
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)

# Generate
inputs = tokenizer(["### Instruction:\nYour question here\n\n### Response:\n"], return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=256)
print(tokenizer.decode(outputs[0]))
```

## Training Infrastructure
- **Provider:** Akash Network (decentralized GPU marketplace)
- **GPU:** NVIDIA H200
- **Cost:** ~$1.50-3.00

Generated by [Akash Unsloth Fine-tune Demo](https://github.com/akash-network).
"""
    try:
        api.upload_file(
            path_or_fileobj=model_card.encode(),
            path_in_repo="README.md",
            repo_id=repo_id,
            repo_type="model",
        )
        logger.info("Model card uploaded")
    except Exception as e:
        logger.warning("Failed to upload model card: %s", e)


def verify_upload(repo_id: str, token: str) -> bool:
    """Verify that uploaded files are accessible on HF Hub."""
    from huggingface_hub import HfApi

    try:
        api = HfApi(token=token)
        files = api.list_repo_files(repo_id=repo_id, repo_type="model")
        logger.info("Verification: %d files found in %s", len(files), repo_id)
        if files:
            return True
        logger.warning("No files found in repo")
        return False
    except Exception as e:
        logger.error("Verification failed: %s", e)
        return False


def serve_http_fallback(lora_dir: str, merged_dir: str, port: int = 8080) -> None:
    """Fall back to HTTP serving if HF upload fails."""
    from http.server import HTTPServer, SimpleHTTPRequestHandler
    import threading

    class JSONHandler(SimpleHTTPRequestHandler):
        def do_GET(self):
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()

            response = {
                "status": "upload_failed",
                "message": "HF upload failed; artifacts available locally",
                "lora_dir": lora_dir,
                "merged_dir": merged_dir,
                "files": {
                    "lora": os.listdir(lora_dir) if os.path.isdir(lora_dir) else [],
                    "merged": os.listdir(merged_dir) if os.path.isdir(merged_dir) else [],
                },
            }
            self.wfile.write(json.dumps(response, indent=2).encode())

        def log_message(self, format, *args):
            logger.info("HTTP: %s", format % args)

    server = HTTPServer(("0.0.0.0", port), JSONHandler)
    logger.info("HTTP fallback server running on port %d", port)
    logger.info("Artifacts available at: lora=%s, merged=%s", lora_dir, merged_dir)
    server.serve_forever()


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Upload fine-tuned model to HuggingFace Hub")
    parser.add_argument("--config", type=str, default="configs/train_config.yaml")
    args = parser.parse_args()

    from src.utils import setup_logging, load_config, validate_env_vars

    setup_logging()
    config = load_config(args.config)

    # Validate required env vars
    env = validate_env_vars(["HF_TOKEN", "HF_REPO_ID"])
    token = env["HF_TOKEN"]
    repo_id = env["HF_REPO_ID"]

    paths_cfg = config["paths"]
    upload_cfg = config["upload"]
    lora_dir = paths_cfg["lora_dir"]
    merged_dir = paths_cfg["merged_dir"]

    logger.info("Starting upload to HuggingFace Hub")
    logger.info("Repo: %s", repo_id)
    logger.info("LoRA dir: %s", lora_dir)
    logger.info("Merged dir: %s", merged_dir)

    # Attempt upload
    success = upload_to_huggingface(
        lora_dir=lora_dir,
        merged_dir=merged_dir,
        repo_id=repo_id,
        token=token,
        push_adapters=upload_cfg.get("push_adapters", True),
        push_merged=upload_cfg.get("push_merged", True),
    )

    if success:
        # Verify upload
        if verify_upload(repo_id, token):
            logger.info("Upload verified successfully!")
        else:
            logger.warning("Upload completed but verification inconclusive")
    else:
        logger.error("HF upload failed, starting HTTP fallback on port 8080")
        serve_http_fallback(lora_dir, merged_dir)


if __name__ == "__main__":
    main()
